 ifnd H_JOYPAD_CONST
H_JOYPAD_CONST = 1

JOYPAD_START = $80
JOYPAD_A     = $40
JOYPAD_B     = $10
JOYPAD_C     = $20
JOYPAD_RIGHT = $08
JOYPAD_LEFT  = $04
JOYPAD_DOWN  = $02
JOYPAD_UP    = $01

 endif
